name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build Rust version
        run: sudo apt-get install -y libusb-1.0-0-dev && cargo build --manifest-path rust/Cargo.toml

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: rust-build
          path: rust/target/debug/
